### ISSUE TITLE
ArgsKwargs schema should be more specific

### ISSUE THREAD

**Issue by federatedsecurecomputing** [federatedsecure/api#1]
The ArgsKwargs schema currently reads:

```yaml
schemas:
    ArgsKwargs:
        type: object
        additionalProperties: true
```

when in fact it should describe a parameter that consists of an array (of args) and of a key value dictionary (kwargs):

```yaml
schemas:
    ArgsKwargs:
        type: object
        required:
            - args
            - kwargs
        properties:
            args:
            type: array
                items: {}
        kwargs:
            type: object
            additionalProperties: true
      additionalProperties: false
```

however the above produces runtime errors in the default connexion webserver stub generated by Swagger tools.
